export const pageNames = {
  ru: { home: "Главная", "how-it-works": "Как это работает", tech: "Технологии", about: "О проекте", download: "Скачать", comparison: "Сравнение", "not-found": "404", roadmap: "Карта разработки", privacy: "Политика конфиденциальности", terms: "Пользовательское соглашение" },
  en: { home: "Home", "how-it-works": "How It Works", tech: "Technology", about: "About Us", download: "Download", comparison: "Comparison", "not-found": "404", roadmap: "Roadmap", privacy: "Privacy Policy", terms: "Terms of Service" },
  es: { home: "Inicio", "how-it-works": "Cómo funciona", tech: "Tecnología", about: "Nosotros", download: "Descargar", comparison: "Comparación", "not-found": "404", roadmap: "Mapa de desarrollo", privacy: "Política de privacidad", terms: "Términos de uso" },
  zh: { home: "首页", "how-it-works": "工作原理", tech: "技术", about: "关于我们", download: "下载", comparison: "对比", "not-found": "404", roadmap: "路线图", privacy: "隐私政策", terms: "用户协议" },
  tr: { home: "Ana Sayfa", "how-it-works": "Nasıl Çalışır", tech: "Teknoloji", about: "Hakkımızda", download: "İndir", comparison: "Karşılaştırma", "not-found": "404", roadmap: "Yol Haritası", privacy: "Gizlilik Politikası", terms: "Kullanıcı Sözleşmesi" },
  hi: { home: "मुख्य", "how-it-works": "यह कैसे काम करता है", tech: "तकनीक", about: "हमारे बारे में", download: "डाउनलोड करें", comparison: "तुलना", "not-found": "404", roadmap: "रोडमैप", privacy: "गोपनीयता नीति", terms: "उपयोग की शर्तें" },
  ar: { home: "الرئيسية", "how-it-works": "كيف يعمل", tech: "التكنولوجيا", about: "من نحن", download: "تنزيل", comparison: "مقارنة", "not-found": "404", roadmap: "خريطة الطريق", privacy: "سياسة الخصوصية", terms: "شروط الاستخدام" },
  pt: { home: "Início", "how-it-works": "Como Funciona", tech: "Tecnologia", about: "Sobre Nós", download: "Baixar", comparison: "Comparação", "not-found": "404", roadmap: "Roteiro", privacy: "Política de Privacidade", terms: "Termos de Uso" },
  fr: { home: "Accueil", "how-it-works": "Comment ça marche", tech: "Technologie", about: "À Propos", download: "Télécharger", comparison: "Comparaison", "not-found": "404", roadmap: "Feuille de route", privacy: "Politique de confidentialité", terms: "Conditions d'utilisation" },
  de: { home: "Startseite", "how-it-works": "Wie es funktioniert", tech: "Technologie", about: "Über Uns", download: "Herunterladen", comparison: "Vergleich", "not-found": "404", roadmap: "Roadmap", privacy: "Datenschutzerklärung", terms: "Nutzungsbedingungen" },
  ja: { home: "ホーム", "how-it-works": "仕組み", tech: "テクノロジー", about: "私たちについて", download: "ダウンロード", comparison: "比較", "not-found": "404", roadmap: "ロードマップ", privacy: "プライバシーポリシー", terms: "利用規約" }
};
